//! Conformance gates for the generated C header, `docs/specs/composition-ir.md`
//! §9.2.
//!
//! The header is the artifact every non-Rust consumer starts from, and it is
//! generated rather than written. Three things can go wrong with a generated
//! artifact, and each has a gate here: it can fall behind its source, it can be
//! *silently incomplete*, and it can be something no C compiler accepts.
//!
//! The middle one is the reason this file exists at all. `cbindgen` does not
//! expand declarative macros, and five accessors here were generated by one --
//! so they, and the `CirBytes` they return, were simply not in the header. No
//! warning, no error; a C consumer just had no way to read any text.

use std::path::{Path, PathBuf};
use std::process::Command;

const CRATE_DIR: &str = env!("CARGO_MANIFEST_DIR");
const HEADER_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/include/composition_ir.h");

/// The header as committed. Bindings and C consumers read this file, and
/// `the_committed_header_matches_what_this_crate_exports` fails when it drifts.
const COMMITTED_HEADER: &str = include_str!("../include/composition_ir.h");

/// The header, from the same crate source a compiler reads.
fn generate() -> String {
    let config = cbindgen::Config::from_file(format!("{CRATE_DIR}/cbindgen.toml"))
        .expect("cbindgen.toml must parse; it is the header's shape");
    let bindings = cbindgen::Builder::new()
        .with_crate(CRATE_DIR)
        .with_config(config)
        .generate()
        .expect("the crate must parse for a header to be generated from it");
    let mut out = Vec::new();
    bindings.write(&mut out);
    String::from_utf8(out).expect("cbindgen emits UTF-8")
}

/// Every `extern "C"` symbol this crate exports, read out of its own source.
///
/// Read rather than listed, for the same reason
/// `every_abi_type_the_ir_publishes_is_in_the_manifest` reads the IR's: a list
/// covers what its author remembered, and the failure this guards against is a
/// *new* export that nobody thought to add to the header.
fn exported_symbols() -> Vec<(String, String)> {
    let src = Path::new(CRATE_DIR).join("src");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&src)
        .unwrap_or_else(|e| {
            panic!(
                "{} must be readable to find its exports: {e}",
                src.display()
            )
        })
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "rs"))
        .collect();
    files.sort();
    // The scan walks a discovered directory, so a module that moves cannot turn
    // it into a no-op -- but an empty directory would still pass everything
    // below vacuously.
    for expected in ["lib.rs", "record.rs"] {
        assert!(
            files.iter().any(|p| p.ends_with(expected)),
            "found {} source files and not {expected}; the scan is looking in the wrong place",
            files.len()
        );
    }

    let mut symbols = Vec::new();
    for path in &files {
        let file = path.file_name().unwrap().to_string_lossy().into_owned();
        let src = std::fs::read_to_string(path).unwrap_or_default();
        for chunk in src.split("#[unsafe(no_mangle)]").skip(1) {
            let Some(at) = chunk.find("extern \"C\" fn ") else {
                continue;
            };
            // The export must be the item this attribute is on. Attributes and
            // doc comments run contiguously into their item, so a blank line
            // before the declaration means the scan has run past the end of one
            // item and into a later one.
            if chunk[..at].contains("\n\n") {
                continue;
            }
            let name: String = chunk[at + "extern \"C\" fn ".len()..]
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                symbols.push((file.clone(), name));
            }
        }
    }
    symbols
}

/// Whether the header declares a function by exactly this name.
///
/// The name must end at the `(` and start at a token boundary. A plain substring
/// search is wrong in both directions here: `cir_node_text` occurs inside
/// `cir_node_text_map(`, so a missing accessor would be reported as present, and
/// a pointer return type puts a `*` immediately before the name, so requiring a
/// leading space reports a declared function as missing.
fn declares(header: &str, name: &str) -> bool {
    header.match_indices(&format!("{name}(")).any(|(at, _)| {
        at == 0
            || !header[..at]
                .chars()
                .next_back()
                .is_some_and(|c| c.is_alphanumeric() || c == '_')
    })
}

/// Every function the header declares.
///
/// Comment lines are dropped first, because the prose in this header names
/// plenty of `cir_…` calls and one of them mentioned with a parenthesis after it
/// would otherwise be read as a declaration.
fn declared_functions(header: &str) -> Vec<String> {
    let mut names = Vec::new();
    for line in header.lines() {
        let t = line.trim_start();
        if t.starts_with("//") || t.starts_with('*') || t.starts_with("/*") || t.starts_with('#') {
            continue;
        }
        let bytes = line.as_bytes();
        let mut start = None;
        for (i, &b) in bytes.iter().enumerate() {
            let word = b.is_ascii_alphanumeric() || b == b'_';
            match (word, start) {
                (true, None) => start = Some(i),
                (false, Some(s)) => {
                    if b == b'(' && line[s..i].starts_with("cir_") {
                        names.push(line[s..i].to_owned());
                    }
                    start = None;
                }
                _ => {}
            }
        }
    }
    names.sort();
    names.dedup();
    names
}

/// The type, enum, and constant names the header puts into C's one global
/// namespace.
fn declared_names(header: &str) -> Vec<String> {
    fn ident(s: &str) -> Option<String> {
        let name: String = s
            .trim_start()
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();
        (!name.is_empty()).then_some(name)
    }
    let mut names = Vec::new();
    for line in header.lines() {
        let line = line.trim_end();
        let name = if let Some(rest) = line.strip_prefix("typedef struct ") {
            // `typedef struct X X;` and `typedef struct X {` alike: the tag is
            // the name, and for the opaque form it is also the alias.
            ident(rest)
        } else if let Some(rest) = line.strip_prefix("typedef enum ") {
            ident(rest)
        } else if let Some(rest) = line.strip_prefix("typedef ") {
            // `typedef uint64_t CirDomain;` -- the alias is the last word.
            rest.trim_end_matches(';')
                .rsplit(' ')
                .next()
                .map(str::to_owned)
        } else if let Some(rest) = line.strip_prefix("} ") {
            ident(rest)
        } else if let Some(rest) = line.strip_prefix("enum ") {
            ident(rest)
        } else if let Some(rest) = line.strip_prefix("#define ") {
            ident(rest)
        } else {
            None
        };
        if let Some(name) = name {
            names.push(name);
        }
    }
    names
}

/// The directory `cargo` writes this profile's artifacts into, derived from
/// where this test binary itself was placed rather than assumed to be
/// `target/debug` -- `CARGO_TARGET_DIR` and `--release` both move it.
fn profile_dir() -> PathBuf {
    let exe = std::env::current_exe().expect("a test binary knows its own path");
    exe.parent() // deps/
        .and_then(Path::parent) // <profile>/
        .expect("a test binary lives under <target>/<profile>/deps")
        .to_path_buf()
}

/// What a C consumer actually links: the two libraries this crate ships, and
/// the system libraries the static one needs alongside it.
///
/// Built here rather than found, because `cargo test` builds the rlib and
/// nothing else: neither would otherwise exist, and a gate whose input is
/// missing is a gate that does not run. `--print native-static-libs` reports
/// what the archive needs to link -- the list differs between macOS and Linux,
/// and guessing it is how this becomes a gate that only runs on one of them.
fn build_libraries() -> (PathBuf, PathBuf, Vec<String>) {
    let mut build = Command::new(env!("CARGO"));
    build.args([
        "rustc",
        "-p",
        "composition-ir-ffi",
        "--lib",
        "--crate-type",
        "staticlib",
        "--crate-type",
        "cdylib",
    ]);
    // The test profile puts this binary under `release/` when `cargo test
    // --release` ran, and an archive built into `debug/` would then be a
    // different build than the one under test -- or missing entirely.
    if profile_dir().ends_with("release") {
        build.arg("--release");
    }
    build.args(["--", "--print", "native-static-libs"]);
    // The note below is read by a machine, so ask for it unstyled. CI sets
    // `CARGO_TERM_COLOR: always`, which this call inherits, and the linker then
    // receives `-lc` with a colour reset welded onto the end of it:
    //
    //     /usr/bin/ld: cannot find -lc\x1b[0m: No such file or directory
    build.env("CARGO_TERM_COLOR", "never");
    let built = build
        .output()
        .expect("cargo must be runnable to build the archive a C consumer links");
    let notes = String::from_utf8_lossy(&built.stderr);
    assert!(
        built.status.success(),
        "building the staticlib failed:\n{notes}"
    );
    let native_libs: Vec<String> = notes
        .lines()
        .find_map(|l| l.split("native-static-libs:").nth(1))
        .unwrap_or_else(|| {
            panic!("rustc did not report native-static-libs; the link would be a guess:\n{notes}")
        })
        .split_whitespace()
        .map(str::to_owned)
        .collect();
    // A token that is not a plain link flag means the note arrived styled after
    // all, and the link below would otherwise fail as an unreadable `cannot
    // find` from the linker rather than as a statement about what went wrong.
    for lib in &native_libs {
        assert!(
            lib.starts_with('-') && !lib.chars().any(char::is_control),
            "rustc reported {lib:?} among the native static libs, which is not a link flag"
        );
    }

    let archive = profile_dir().join("libcomposition_ir_ffi.a");
    let shared = profile_dir().join(format!(
        "{}composition_ir_ffi{}",
        std::env::consts::DLL_PREFIX,
        std::env::consts::DLL_SUFFIX
    ));
    for built in [&archive, &shared] {
        assert!(
            built.exists(),
            "{} was not produced; a C consumer has nothing to link",
            built.display()
        );
    }
    (archive, shared, native_libs)
}

/// Every `cir_…` function the built library actually defines.
///
/// The library, not the source text. Reading the source is what a scan would
/// naturally do and is exactly what fails here: an export generated by a
/// `macro_rules!` is a symbol in the library and is not a `fn` anywhere in the
/// source, so a text scan reports the surface as complete while the header is
/// missing five calls. That is the bug this file was written for, and a check
/// that cannot see it is decoration.
///
/// The shared library rather than the archive, for two reasons. Its export
/// table *is* the ABI surface -- an archive also carries every internal symbol
/// of everything statically linked into it. And an archive still holds
/// `compiler_builtins` members as LLVM bitcode, which the host `nm` is a
/// different LLVM version from and refuses outright.
fn defined_symbols(library: &Path) -> Vec<String> {
    let listed = Command::new("nm")
        .arg("-g")
        .arg(library)
        .output()
        .expect("nm must be present to read the symbols the library defines");
    assert!(
        listed.status.success(),
        "nm failed on {}:\n{}",
        library.display(),
        String::from_utf8_lossy(&listed.stderr)
    );
    let mut names: Vec<String> = String::from_utf8_lossy(&listed.stdout)
        .lines()
        .filter_map(|line| {
            // `<addr> T <name>`, where `T` is a defined external text symbol.
            // Mach-O prefixes every symbol with an underscore and ELF does not.
            let mut cols = line.split_whitespace();
            let name = cols.nth_back(0)?;
            (cols.next_back()? == "T").then(|| name.strip_prefix('_').unwrap_or(name).to_owned())
        })
        .filter(|name| name.starts_with("cir_"))
        .collect();
    names.sort();
    names.dedup();
    names
}

/// The generated header must be the header in the tree. Regenerate with
/// `UPDATE_HEADER=1 cargo test -p composition-ir-ffi`.
///
/// Unlike `abi/layout.json` this file is not per-target: a C compiler computes
/// offsets for whatever it is compiling for, so there is one header for every
/// ABI and no target block to guard.
#[test]
fn the_committed_header_matches_what_this_crate_exports() {
    let generated = generate();
    if COMMITTED_HEADER == generated {
        return;
    }
    if std::env::var("UPDATE_HEADER").is_ok() {
        std::fs::write(HEADER_PATH, &generated).expect("rewrite the header");
        panic!(
            "header rewritten; review the diff -- it is the ABI every consumer compiles against"
        );
    }
    let first = COMMITTED_HEADER
        .lines()
        .zip(generated.lines())
        .enumerate()
        .find(|(_, (a, b))| a != b)
        .map(|(i, (a, b))| format!("line {}:\n  committed: {a}\n  generated: {b}", i + 1))
        .unwrap_or_else(|| "one is a prefix of the other".to_string());
    panic!(
        "the C ABI changed and include/composition_ir.h did not.\n{first}\n\n\
         Regenerate with UPDATE_HEADER=1 cargo test -p composition-ir-ffi."
    );
}

/// A generated header that is *missing* a function is the failure mode with no
/// symptom: nothing fails to compile, nothing fails to link, and the call is
/// merely unreachable from C. It has happened here once already -- five
/// accessors written as one `macro_rules!`, which `cbindgen` does not expand.
///
/// Checked against the library's own symbol table, which is the only statement
/// of what it exports that no spelling in the source can hide.
#[test]
fn every_symbol_the_library_defines_is_declared_in_the_header() {
    let (_, shared, _) = build_libraries();
    let defined = defined_symbols(&shared);
    assert!(
        defined.len() >= 25,
        "the archive defines only {} cir_ symbols; reading it stopped working: {defined:?}",
        defined.len()
    );
    for name in &defined {
        assert!(
            declares(COMMITTED_HEADER, name),
            "the library defines `{name}` and the header does not declare it, \
             so no C consumer can call it"
        );
    }
}

/// The naming rule from §9 -- and it is load-bearing rather than cosmetic.
/// `every_symbol_the_library_defines_is_declared_in_the_header` finds this
/// crate's exports in an archive that also holds all of `std` by taking the
/// `cir_` prefix as the boundary. An export named anything else is one that
/// check would not look at.
#[test]
fn every_exported_call_is_named_for_its_subject() {
    let symbols = exported_symbols();
    assert!(
        symbols.len() >= 25,
        "found only {} exports by reading the source; the scan stopped working",
        symbols.len()
    );
    for (file, name) in &symbols {
        let parts: Vec<&str> = name.split('_').collect();
        assert!(
            parts.len() >= 3 && parts[0] == "cir" && parts[1..].iter().all(|p| !p.is_empty()),
            "{file}: `{name}` is exported but is not cir_<subject>_<verb>; \
             the completeness check finds exports by that prefix and would not see it"
        );
    }
}

/// A C consumer has exactly one global namespace, and `Rect`, `Id`, and `Space`
/// are names it will already have spent. Every name this header introduces is
/// therefore `Cir`-prefixed -- which is a per-type list in `cbindgen.toml`,
/// because a blanket prefix also renames the types already spelled `Cir…` and
/// publishes `CirCirBytes`. A list falls behind; this is what stops it.
#[test]
fn every_type_the_header_declares_is_prefixed() {
    let names = declared_names(COMMITTED_HEADER);
    assert!(
        names.len() >= 15,
        "found only {} declared names in the header; the scan stopped working: {names:?}",
        names.len()
    );
    for name in &names {
        // The include guard is the one name that is not a C identifier a
        // consumer can collide with by using the library.
        if name == "COMPOSITION_IR_H" {
            continue;
        }
        assert!(
            name.starts_with("Cir"),
            "the header publishes `{name}` into C's global namespace unprefixed; \
             add it to [export.rename] in cbindgen.toml"
        );
    }
}

/// The two claims a Rust test cannot make about a C header: that a C compiler
/// accepts it, and that every function it declares is a symbol the library
/// actually defines.
///
/// The translation unit names the union of what the library defines and what
/// the header declares, which is what makes both directions fail loudly rather
/// than one. A name the library defines and the header omits is an undeclared
/// identifier at compile time; a name the header declares and the library never
/// defines resolves nowhere at link time. The second cannot be found by
/// comparing text at all -- only a linker knows.
#[test]
fn a_c_consumer_compiles_against_the_header_and_links_every_symbol() {
    let (archive, shared, native_libs) = build_libraries();
    let mut names = defined_symbols(&shared);
    names.extend(declared_functions(COMMITTED_HEADER));
    names.sort();
    names.dedup();
    assert!(
        names.len() >= 25,
        "only {} symbols to check; the scans that feed this stopped working",
        names.len()
    );

    let out = profile_dir().join("c-consumer");
    std::fs::create_dir_all(&out).expect("create the C consumer's build directory");

    // Function pointers, not `void *`: a function-to-object-pointer cast is not
    // something ISO C guarantees, and this compiles with -pedantic -Werror.
    // Nothing is ever called through them -- taking the address is what forces
    // the linker to resolve each one.
    let mut c =
        String::from("#include \"composition_ir.h\"\n\nstatic void (*const symbols[])(void) = {\n");
    for name in &names {
        c.push_str(&format!("    (void (*)(void)){name},\n"));
    }
    c.push_str("};\n\nint main(void) {\n    return symbols[0] == 0;\n}\n");
    let c_path = out.join("consumer.c");
    std::fs::write(&c_path, &c).expect("write the C consumer");

    // C first, then C++. `cpp_compat = true` puts an `extern "C"` guard in the
    // header, and a guard nobody compiles is a promise nobody has checked.
    for (compiler, std_flag, lang, obj) in [
        ("cc", "-std=c99", "c", "consumer.o"),
        ("c++", "-std=c++11", "c++", "consumer.cpp.o"),
    ] {
        let obj = out.join(obj);
        let compiled = Command::new(compiler)
            .args([std_flag, "-Wall", "-Wextra", "-Werror", "-pedantic"])
            .arg(format!("-I{CRATE_DIR}/include"))
            // Before the input, or the driver ignores it -- and one `.c` file
            // compiled twice as C is not the C++ check this claims to be.
            .args(["-x", lang, "-c"])
            .arg(&c_path)
            .arg("-o")
            .arg(&obj)
            .output()
            .unwrap_or_else(|e| panic!("{compiler} must be present to check the header: {e}"));
        assert!(
            compiled.status.success(),
            "{compiler} rejected the generated header:\n{}",
            String::from_utf8_lossy(&compiled.stderr)
        );

        let linked = Command::new(compiler)
            .arg(&obj)
            .arg(&archive)
            .args(&native_libs)
            .arg("-o")
            .arg(out.join("consumer"))
            .output()
            .expect("link the C consumer");
        assert!(
            linked.status.success(),
            "the header declares a symbol the library does not define ({compiler}):\n{}",
            String::from_utf8_lossy(&linked.stderr)
        );
    }
}
